name: HexoCI

on: 
  push:
    branches:
      - master
      
jobs:
  build: 
    runs-on: ubuntu-latest 
        
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache
    
    - env:
        HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXOCI }}
    - run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/hexoci 
        chmod 600 ~/.ssh/hexoci
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'lucifer9735' 
        git config --global user.email 'lucifer9735@gmail.com'
        npm install hexo-cli -g
        npm install
        hexo clean
        hexo generate 
        hexo deploy
